### ISSUE TITLE
'Parser' Initializer is inaccessible due to 'internal ' protection level

### ISSUE THREAD

**Issue by Jimmy-Glorang** [LambdaDigamma/swift-prosemirror#1]
I'm trying to use Parser() but I 've got an error message
```
'Parser' Initializer is inaccessible due to 'internal ' protection level
```
So I made a little change in Parser like this to use it  in public.
```
public class Parser {
    private let decoder: JSONDecoder = .defaultProseMirrorDecoder
    public init() {}
// extra implementation ...
```
Then parser seemed to work, but I got another error message
```
Accessing Environment<Color>'s value outside of being installed on a View. This will always read the default value and will not update.
```

Is it because of not using Parser() properly? I need some answer for this.

Thank for your support.

**Comment by LambdaDigamma** [comment]
Hey!

You are right. Listing the parser example is somewhat misleading.
This package is intended for the use of SwiftUI.
You can just decode a basic Prosemirror document in a decodable struct and render it in a SwiftUI view via `document.render()`.

```swift
import ProseMirror

struct YourModel: Decodable {
    let document: Document
}
```

```swift
import SwiftUI
import ProseMirror

struct YourView: View {

    let document: Document

    var body: some View {
        document.render()
    }

}
```

I will update the readme and remove the parser as it is mainly internal in the current state of the package.

Feel free to add other functionality and send a pull request.
Hope this helps!

**Comment by Jimmy-Glorang** [comment]
Oh- there is the simpler way. Thank you so much.
